faggots = {
    "GoldenLemon4433",
    "Mintpopser_Novich",
    "SwornExodus",
    "TacticalFunds", 
    "WarAkuji",
    "MetatableIndex",
    "ExecutiveFunds",
    "Sullixam",
    "comemyway157",
    "Scorpio0270",
    "HanzoTango",
    "hanxwang",
    "GodYPlayzRB",
    "herodue",
    "lolcrafter123456789",
    "RAZOR_BULL3T",
    "mycoal",
    "Reptilefunds",
    "Mg35t",
    "agresywnytoster2505",
    "JudicialFunds",
    "FrostFunds",
    "YesImFlavuh",
    "yanidef",
    "starwardon",
    "Plaguedfunds",
    "Niekv167",
    "GamingFunds",
    "EraserSoul",
    "ByteFunds",
    "BeautifullyBalanced",
    "animalplanet30",
    "AgentFunds",
    "ByteFunds"
}

return faggots
